version: '3'
services:
  app1:
    container_name: a_main_app1
    build: . 
    environment:
      - PORT=8080
  # app2:
  #   container_name: a_main_app2
  #   build: . 
  #   environment:
  #     - PORT=8081
  redis:
    container_name: a_redis
    image: redis
    restart: always
  nginx:
    restart: always
    container_name: a_nginx
    image: nginx
    ports:
      - "80:8888"
    depends_on:
      - app1
      # - app2